# Generated by Django 2.1 on 2019-01-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Divition',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divition.Divition'),
        ),
    ]
