# Generated by Django 2.1 on 2019-01-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(help_text='Type number between 1 to 10', max_length=5)),
                ('Divition_Name', models.CharField(max_length=5)),
            ],
        ),
    ]
