# Generated by Django 2.1 on 2019-01-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190114_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Teacher_Name',
        ),
    ]
